function bedpostx_pdf_path = bedpostx_plot(job_dir,dwmri_file,mask_file,mean_fsumsamples_file,dyads_files,meanfsamples_files,fsl_path,bedpostx_params,num_fibres)
    % This will plot outputs of bedpostx
    
    % Create "PDF" directory
    pdf_dir = system_utils.directory(job_dir,'PDF');
    pdf_dir.mkdir();

    % Load data     
    mask_vol = nifti_utils.load_untouch_nii_vol_scaled(mask_file.get_path(),'logical');  
    mean_fsumsamples_vol = nifti_utils.load_untouch_nii_vol_scaled(mean_fsumsamples_file.get_path(),'double'); 
    dyads_vols = {};
    meanfsamples_vols = {};   
    for i = 1:num_fibres
        dyads_vols{i} = nifti_utils.load_untouch_nii4D_vol_scaled(dyads_files(i).get_path(),'double'); %#ok<AGROW>
        meanfsamples_vols{i} = nifti_utils.load_untouch_nii_vol_scaled(meanfsamples_files(i).get_path(),'double'); %#ok<AGROW>
    end     
    xform_RAS = nifti_utils.get_voxel_RAS_xform(dwmri_file.get_path());
    
    % Get visualizer    
    dv = dwmri_visualizer(vertcat(dyads_vols,[ones(size(mask_vol)),meanfsamples_vols(2:end)]), ...
                          mean_fsumsamples_vol + 0.2, ... 
                          mask_vol, ...
                          xform_RAS, ...
                          'directions', ...
                          vertcat(mat2cell(distinguishable_colors(num_fibres,{'w','k'}),ones(1,num_fibres),3)', ...
                                  num2cell(0.25*ones(1,num_fibres)), ...
                                  num2cell([1 0.05*ones(1,num_fibres-1)])));
                               
    % Make the plot
    f = dwmri_axial_coronal_plot(dv, ...
                                 {'BedpostX', ...
                                 ['   FSL path: ' fsl_path ], ...
                                 ['   bedpostx params: ' bedpostx_params], ...
                                 '', ...
                                 '', ...
                                 '', ...
                                 'Justin Blaber', ...
                                 'justin.blaber@vanderbilt.edu', ...
                                 'Probabilistic diffusion tractography with multiple fibre orientations: What can we gain? (Behrens et al 2013)', ...
                                 'N/A', ...
                                 'N/A'});
                             
    % Sometimes figures are saved before everything is "set". This might
    % fix it?
    drawnow
    
    pdf_file = system_utils.file(pdf_dir,'bedpostx.pdf');
    print(f,'-painters','-dpdf','-r600',pdf_file.get_path());
    
    % Return path
    bedpostx_pdf_path = pdf_file.get_path();
end
